[project]
name = "cds-core"
version = "0.1.0"
description = "Core tools for data stories"
readme = "README.md"
authors = [
    { name = "CosmicDS Developers", email = "pudomprasert@cfa.harvard.edu" }
]
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "echo>=0.9.0",
    "glue-core>=1.22.0",
    "glue-jupyter>=0.23.1",
    "glue-plotly[jupyter]>=0.12.2",
    "httpx>=0.28.1",
    "numpy>=2.2.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
